grpc:
  server:
    port: 9898
server:
  port: 8089
spring:
  application:
    name: car-server
  datasource:
    driverClassName: org.h2.Driver
    password: sa
    url: jdbc:h2:mem:car;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true