server:
  port: 8086
spring:
  application:
    name: car-client
grpc:
  client:
    car-server:
      address: 'static://127.0.0.1:9898'
      negotiationType: plaintext
      enableKeepAlive: true
      keepAliveWithoutCalls: true
